import { X, Copy, Download, Mail, Mic } from "lucide-react";
import { useState } from "react";

interface FinalReportScreenProps {
  isOpen: boolean;
  onClose: () => void;
  reportDate?: string;
  referenceNumber?: string;
  fromField?: string;
  toField?: string;
  viaField?: string;
  subjectField?: string;
  referenceText?: string;
  backgroundText?: string;
  topic?: string;
  discussionText?: string;
  recommendationText?: string;
  sustainTopic?: string;
  sustainDiscussion?: string;
  sustainRecommendation?: string;
  contactName?: string;
  contactPhone?: string;
  contactEmail?: string;
}

export function FinalReportScreen({
  isOpen,
  onClose,
  reportDate = "04JAN2026",
  referenceNumber = "",
  fromField = "Rank F Name MI L Name, Billet",
  toField = "Operations Officer",
  viaField = "Rank Name, Billet",
  subjectField = "AFTER ACTION REPORT FOR EVENT CONDUCTED FROM JANUARY 6, 2026",
  referenceText = "",
  backgroundText = "This report summarizes observation(s) recorded on January 6, 2026. The observations are categorized into areas for improvement or practices to sustain. Specific objectives during this observation include:\n• [objective]\n• [objective]\n• [objective]",
  topic = "AI Bias or Risk",
  discussionText = "I saw several participants struggling to navigate the information system during the event. Most were unable to locate and share critical information in a timely manner and mistakes were made. This can compromise data quality, integrity and availability of information.",
  recommendationText = "Enhance training for information systems and intelligence tools by setting measurable standards and coordinating with local authorities for annual updates based on modern capabilities and user feedback. Improve transparency and efficiency in decision-making.\n\nEstablish a support network of modern intelligence analysts, data specialists, trainers, and security experts to share best practices and ensure annual training stays relevant and effective.",
  sustainTopic = "[Topic Name]",
  sustainDiscussion = "[Discussion text]",
  sustainRecommendation = "[Recommendation text]",
  contactName = "Rank F Name MI L Name",
  contactPhone = "(XXX) XXX-XXXX",
  contactEmail = "email@usmc.mil"
}: FinalReportScreenProps) {
  const [isRecording, setIsRecording] = useState(false);

  if (!isOpen) return null;

  const handleCopy = () => {
    const reportContent = document.getElementById("final-report-content")?.innerText || "";
    navigator.clipboard.writeText(reportContent);
    alert("Report copied to clipboard!");
  };

  const handleSave = async () => {
    handleDownload();
  };

  const handleDownload = () => {
    const reportContent = document.getElementById("final-report-content")?.innerText || "";
    const blob = new Blob([reportContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `After_Action_Report_${reportDate}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleEmail = () => {
    const reportContent = document.getElementById("final-report-content")?.innerText || "";
    const userEmail = localStorage.getItem("subscriberEmail") || "";

    const emailBody = `${reportContent}
\n---\nThis report was generated by ORA AI Leadership Agent\nDate: ${new Date().toLocaleDateString("en-US", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric"
    })}`;

    const mailtoLink = `mailto:${userEmail}?subject=${encodeURIComponent(
      subjectField
    )}&body=${encodeURIComponent(emailBody)}`;

    window.location.href = mailtoLink;
  };

  const toggleRecording = () => {
    setIsRecording(!isRecording);
  };

  return (
    <div className="absolute inset-0 bg-white dark:bg-gray-900 z-[80] overflow-y-auto">
      {/* Header Bar */}
      <div className="sticky top-0 bg-black text-white px-3 py-2 z-10">
        <div className="flex items-center justify-between">
          <h1 className="text-sm font-semibold ml-1.5">Preview</h1>
          <div className="flex items-center gap-1.5 mr-1.5">
            <button
              onClick={handleCopy}
              className="bg-purple-100 text-purple-700 px-2.5 py-1.5 rounded-lg text-[11px] font-semibold flex items-center gap-1 hover:bg-purple-200 transition-colors"
            >
              <Copy className="size-3" />
              Copy
            </button>
            <button
              onClick={handleSave}
              className="bg-purple-600 text-white px-2.5 py-1.5 rounded-lg text-[11px] font-semibold flex items-center gap-1 hover:bg-purple-700 transition-colors"
            >
              <Download className="size-3" />
              Save
            </button>
            <button
              onClick={handleEmail}
              className="bg-purple-500 text-white px-2.5 py-1.5 rounded-lg text-[11px] font-semibold flex items-center gap-1 hover:bg-purple-600 transition-colors"
            >
              <Mail className="size-3" />
              Email
            </button>
            <button
              onClick={onClose}
              className="text-white hover:text-purple-300 transition-colors ml-1"
            >
              <X className="size-5" />
            </button>
          </div>
        </div>
      </div>

      {/* Report Content */}
      <div id="final-report-content" className="p-4 text-sm text-gray-900 dark:text-gray-100">
        {/* ...existing report layout... */}
      </div>
    </div>
  );
}